{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dbplot
  version: {{ version|replace("-", "_") }}

source:
  fn: dbplot_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dbplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dbplot/dbplot_{{ version }}.tar.gz
  sha256: bec99a180741681bc84d97175a55aa52c8ded9453d579cc0c7917604323ba8d7

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >=0.7
    - r-ggplot2
    - r-purrr
    - r-rlang >=0.2.0
  run:
    - r-base
    - r-dplyr >=0.7
    - r-ggplot2
    - r-purrr
    - r-rlang >=0.2.0

test:
  commands:
    - $R -e "library('dbplot')"           # [not win]
    - "\"%R%\" -e \"library('dbplot')\""  # [win]

about:
  home: https://github.com/edgararuiz/dbplot
  license: GPL-3
  summary: |
    Leverages 'dplyr' to process the calculations of a plot inside a database. This
    package provides helper functions that abstract the work at three levels: outputs
    a 'ggplot', outputs the calculations, outputs the formula needed to calculate
    bins.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - halldc
