# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J1cxKv3hCg6UqcCbZfTYf1cwkmWNvJCz4STU02GB5NN5Z3ZLJyGFbW6IVU5HDm/2nky0QKufTxVYreH9JpXuXEs27bdUqOGZz3sEIgWl7SgmHgh8WeS/3sxqnjZ6DAzIBPOEH75FKQvekzYIu2eiOqG0pdU9fbzKj7cNRQuKhYFsjk7jN1tmyBR4x/YCEr9JO0tUySqkyRw3LHBqhTMsTXLrLo1DQkt8ZRLF3xz+8tLvlu9wctOq3WtexV2ezgIhc4gB7uyl4pEPxNo11HaSSB/CYNYYVw9SmcIvWfWes8Tmu4Vh2N3OU3E6crk/GmFFYkmow+Kkr4NHfHIOjLTYTfvdRi8qg2/NrSyhW1yYfu5PnLoHXPCvvNT3BVsewrOhGFsG+rDsSxLp101DYi6qiJkaSdJZ4O4T0ri71xJwP4aGv7vCMd2iVaOmhlgbKOBhn03w+9+Z5lYG+10FReNUjgOoNNLtD8n9bBLW4I1BjLjJ99b0FUXsGTiheDLOZIPrQgdM+B1pkFjEWnGNlnBtIuCwyx1PWOM7SuZjthdNuvUJzW27TgzrdXMsTOSZXVXssp89DxN2+UeXaGfkvjxXdNCWZmImVj4k/MeKsBp25Qf2w0nD7dTVBTjyitV7eFGW+Rn1rq465jLKnGEfwIPQzxEzKP6amxLuzSRnv1NDyNk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
