appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J1cxKv3hCg6UqcCbZfTYf1cwkmWNvJCz4STU02GB5NN5Z3ZLJyGFbW6IVU5HDm/2nky0QKufTxVYreH9JpXuXEs27bdUqOGZz3sEIgWl7SgmHgh8WeS/3sxqnjZ6DAzIBPOEH75FKQvekzYIu2eiOqG0pdU9fbzKj7cNRQuKhYFsjk7jN1tmyBR4x/YCEr9JO0tUySqkyRw3LHBqhTMsTXLrLo1DQkt8ZRLF3xz+8tLvlu9wctOq3WtexV2ezgIhc4gB7uyl4pEPxNo11HaSSB/CYNYYVw9SmcIvWfWes8Tmu4Vh2N3OU3E6crk/GmFFYkmow+Kkr4NHfHIOjLTYTfvdRi8qg2/NrSyhW1yYfu5PnLoHXPCvvNT3BVsewrOhGFsG+rDsSxLp101DYi6qiJkaSdJZ4O4T0ri71xJwP4aGv7vCMd2iVaOmhlgbKOBhn03w+9+Z5lYG+10FReNUjgOoNNLtD8n9bBLW4I1BjLjJ99b0FUXsGTiheDLOZIPrQgdM+B1pkFjEWnGNlnBtIuCwyx1PWOM7SuZjthdNuvUJzW27TgzrdXMsTOSZXVXssp89DxN2+UeXaGfkvjxXdNCWZmImVj4k/MeKsBp25Qf2w0nD7dTVBTjyitV7eFGW+Rn1rq465jLKnGEfwIPQzxEzKP6amxLuzSRnv1NDyNk=}
